@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### ConceitoManualController HOME

# @name ConceitoManualControllerHome
GET {{baseUrl}}/conceitos-manual


### ConceitosAutomaticoController HOME
GET {{baseUrl}}/conceitos-automatico

### SolucionaExemplo
GET {{baseUrl}}/home/exemplo

### SolucionaHome
# @name SolucionaHome
GET {{baseUrl}}/conceitos-manual

### TODOS os recados
# @name Recados
GET {{baseUrl}}/recados
?limit=10
&offset=0

### UM recado
# @name UmRecado
GET {{baseUrl}}/recados/2

###
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Tambem amo muito",
    "deId": 1,
    "paraId": 3
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/7
Content-Type: application/json

{
    "lido": false,
    "texto": "deu certo"
}
### Remove um cadastro
DELETE {{baseUrl}}/recados/

### Criar uma pessoa
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "nome": "Bruno",
    "email": "bruno@mail.com",
    "password":"lerolerolero"
}

### Buscar todas as pessoas
GET {{baseUrl}}/pessoas

### Busca uma pessoa pelo id
GET {{baseUrl}}/pessoas/2

### Remove uma pessoa
DELETE {{baseUrl}}/pessoas/2

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/3
Content-Type: application/json

{
    "password":"bilulilu"
}

